### ISSUE TITLE
Node engine version

### ISSUE THREAD

**Issue by wKovacs64** [durancristhian/meetup-randomizer#10]
The Node version in the `engines` stanza of `package.json` is set to `"6"`. This prevents [yarn](https://yarnpkg.com) from adding `meetup-randomizer` as a dependency when running in Node 7. Would it be possible to change it to `">= 6"` or is it truly restricted to 6.x? (I tested it briefly on 7.5.0 and it behaved as expected, but my testing was by no means extensive.)

Here is the yarn output, for reference:
```sh
error meetup-randomizer@2.8.0: The engine "node" is incompatible with this module. Expected version "6".
error Found incompatible module
```

Thanks.

**Comment by durancristhian** [comment]
Hi @wKovacs64!

I''ll fix this ASAP. Thanks for reporting! 😉

**Comment by durancristhian** [comment]
Hello again,

I've updated the package, now you should be able to use it with yarn and any node version starting by 6 or greater.

**Comment by wKovacs64** [comment]
Great, thanks!
