### ISSUE TITLE
Events with no qualified attendees will error

### ISSUE THREAD

**Issue by wKovacs64** [durancristhian/meetup-randomizer#17]
When attempting to get a random attendee from an event that doesn't have any confirmed non-hosts attending, meetup-randomizer errors out with the following:

```
There was an error when we tried to show the winner's image
Error description: Cannot read property 'photoURL' of undefined
undefined
```

**Comment by durancristhian** [comment]
Hi! Thank you very much for your contributions! 👍

**Comment by wKovacs64** [comment]
No problem, happy to help. Think you'll release a new version soon so I can take advantage of the new error handling downstream? :)

**Comment by durancristhian** [comment]
After merging your change, a new version was released `v2.10.0` 😎

**Comment by wKovacs64** [comment]
Sweet. :+1:

**Comment by durancristhian** [comment]
btw, I added you as a contributor in the README 👍🏽
